import numpy as np
import xml.etree.ElementTree as ET
from collections import defaultdict

def modify_contact_parameters(input_file, output_file, modifications):
    """
    Modify contact_gaussian parameters in SMOG2 XML file
    
    Args:
        input_file: Input XML file path
        output_file: Output XML file path
        modifications: Dictionary of {(i,j): {'A': new_A, 'sigmaG': new_sigmaG}}
    """
    # Parse XML file
    tree = ET.parse(input_file)
    root = tree.getroot()

    # Find contact_gaussian section
    contact_gaussian = root.find('./contacts/contacts_type[@name="contact_gaussian"]')
    if contact_gaussian is None:
        raise ValueError("contact_gaussian section not found in XML")

    # Modify interactions
    modified_count = 0
    for interaction in contact_gaussian.findall('interaction'):
        i = interaction.get('i')
        j = interaction.get('j')
        r0 = float(interaction.get('r0'))
        
        if (i, j) in modifications:
            params = modifications[(i, j)]
            interaction.set('A', str( max(params['A'], 0.1) ))
            interaction.set('sigmaG', str( min(r0*0.15, params['sigmaG']) ))
            modified_count += 1

    # Save modified XML
    tree.write(output_file, encoding='UTF-8', xml_declaration=True)
    print(f"Modified {modified_count} interactions. Saved to {output_file}")

def rescale_contact_parameters(contacts_file, pae_file, npow=2, sigma_rescale=True):
    """
    Rescales contact_gaussian parameters in SMOG2 XML file based on AF2 predicted PAE.

    Args:
        contacts_file: File containing the residue pairs forming contacts.
        pae_file: AF2-predicted PAE file.
        npow: Exponent for rescaling contact strength based on PAE.

    Returns:
        A dictionary of rescaled contact_gaussian parameters: 
            {(i,j): {'A': new_A, 'sigmaG': new_sigmaG}} 
            where (i,j) represents the residue pair.
    """

    # Load contacts file generated by smog2
    pairs = np.loadtxt(contacts_file, usecols=(1, 3), dtype=int)

    # Load AF2-predicted PAE and symmetrize
    pae = np.load(pae_file)
    pae = 0.5 * (pae + pae.T) 

    # Calculate rescaled contact strengths based on PAE
    eij = np.power(pae[pairs[:, 1] - 1, pairs[:, 1] - 1], -npow) 
    eij *= len(pairs) / np.sum(eij) 

    # Create a dictionary of modified parameters
    if sigma_rescale:
        modifications = {
            (str(pair[0]), str(pair[1])): {'A': eij[i], 'sigmaG': pae[pair[0] - 1, pair[1] - 1]*0.05} 
            for i, pair in enumerate(pairs)
        }
    else:
        modifications = {
            (str(pair[0]), str(pair[1])): {'A': eij[i], 'sigmaG': 0.05} 
            ## (str(pair[0]), str(pair[1])): {'A': max(eij[i], 0.05), 'sigmaG': 0.05}
            for i, pair in enumerate(pairs)
        }

    return modifications


if __name__ == "__main__":

    input_xml = "CA_gau.xml"
    contacts_file ="CA_gau.contacts"
    pae_file ="pae_1.npy"

    output_xml = "pae1_gau0.xml"
    modifications = rescale_contact_parameters("CA_gau.contacts", "pae_1.npy", 1, False)
    modify_contact_parameters(input_xml, output_xml, modifications)

    output_xml = "pae2_gau0.xml"
    modifications = rescale_contact_parameters("CA_gau.contacts", "pae_1.npy", 2, False)
    modify_contact_parameters(input_xml, output_xml, modifications)

    output_xml = "pae3_gau0.xml"
    modifications = rescale_contact_parameters("CA_gau.contacts", "pae_1.npy", 3, False)
    modify_contact_parameters(input_xml, output_xml, modifications)

    output_xml = "pae1_gau1.xml"
    modifications = rescale_contact_parameters("CA_gau.contacts", "pae_1.npy", 1, True)
    modify_contact_parameters(input_xml, output_xml, modifications)

    output_xml = "pae2_gau1.xml"
    modifications = rescale_contact_parameters("CA_gau.contacts", "pae_1.npy", 2, True)
    modify_contact_parameters(input_xml, output_xml, modifications)
